#!/bin/sh
cd multipass/monome_euro/meadowphysics
make clean
make
mkdir ../../../chrono-sage
cp multipass_mp.hex ../../../chrono-sage/chrono-sage.hex
cp multipass_mp.hex ../../../chrono-sage.hex
make clean
cd ../../../
cp flash chrono-sage/
cp update_firmware.command chrono-sage/
zip -r -X chrono-sage.zip chrono-sage
rm -rf chrono-sage/
